### ISSUE TITLE
[ISSUE] -  bulkQuery.on is not a function

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/SFDX-Data-Move-Utility#1167]
Hello @hknokh2 , i found an issue with latest version (5.1.2) :(

My export.json

```json
{
  "sfdxHardisLabel": "Anonymize Contacts after UAT Refresh",
  "sfdxHardisDescription": "",
  "objects": [
    {
      "query": "SELECT Id, Name, Email FROM Contact",
      "operation": "Update",
      "externalId": "Id",
      "mockFields": [
        {
          "name": "Email",
          "pattern": "email"
        }
      ],
      "updateWithMockData": true
    }
  ],
  "allOrNone": true
}
```

Command: 

`sf sfdmu:run --sourceusername nicolas.vuillamy.ext@xxx.uatrun --targetusername csvfile -p scripts/data/AnonymizeContacts --noprompt`

Result:

```shell
[16:26:29.964] ===== MIGRATION JOB STARTED =====
[16:26:29.970] Execution of the command sfdmu:run has been started.
[16:26:29.971] Loading and validating the export.json script (xxx/export.json)...
[16:26:30.170]  
[16:26:30.171] ===== OBJECT SET #1 STARTED =====
[16:26:30.171]  
[16:26:30.171] SOURCE: nicolas.vuillamy.ext@vusion.com.uatrun (sandbox).
[16:26:30.171] TARGET: csvfile.
[16:26:30.173]  
[16:26:30.174] Preparing data migration job ...
[16:26:30.174] Building the migration strategy ...
[16:26:30.175] Connecting to the nicolas.vuillamy.ext@xxx.uatrun
[16:26:30.312] Successfully connected to the nicolas.vuillamy.ext@xxx.uatrun.
[16:26:30.313] Loading Core Add-On Module declarations ...
[16:26:30.320] {Contact} Fetching metadata (SOURCE) ...
[16:26:30.852] {FieldDefinition} Using REST API (v65.0) to retrieve the data ...
[16:26:30.915] Validation of the source CSV files ...
[16:26:30.916]  
[16:26:30.916] ANALYSING DATA...
[16:26:30.916] {Contact} Processing the object ...
[16:26:30.919] {Contact} Using REST API (v65.0) to retrieve the data ...
[16:26:31.107] {Contact} The original query string of this object is returning 138276 records from the SOURCE org.
[16:26:31.107] Preparing of the data migration job has been completed.
┌─────────────┬──────────────┬──────────────┐
│ Query Order │ Delete Order │ Update Order │
├─────────────┼──────────────┼──────────────┤
│ Contact     │              │ Contact      │
└─────────────┴──────────────┴──────────────┘

[16:26:31.143]
[16:26:31.144] Triggering Add-On events ...
[16:26:31.144] No Add-On modules found to run.
[16:26:31.144]
[16:26:31.145] Ready to process the data.
[16:26:31.145]
[16:26:31.146] Deleting old data from the Target ...
[16:26:31.146] Deleting data was skipped.
[16:26:31.146]
[16:26:31.147] SOURCE:
[16:26:31.147] =============
[16:26:31.147]
[16:26:31.148] ===== Fetching the data (STAGE 1) =====
[16:26:31.149] {Contact} Fetching the SOURCE data from Org (STAGE 1: all records) ...
[16:26:31.150] {Contact} Query string: SELECT Id, Name, Email FROM Contact.
[16:26:31.150] {Contact} Using Bulk API Query (v65.0) to retrieve the data ...
[16:26:31.155] ===== MIGRATION JOB ENDED =====
[16:26:31.155] [ERROR] Execution of the command has aborted due to unexpected error: bulkQuery.on is not a function.
[16:26:31.156] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[16:26:31.156] Total time elapsed: 00h 00m 01s 192ms .
```

Note: the same config & command works fine with v4.39.0
